package content.global.activity.champion.plugin

import shared.consts.Items
import shared.consts.NPCs
import shared.consts.Vars

/**
 * The champion's challenge data.
 */
enum class ChampionDefinition(val scrollId: Int, val npcId: Int, val xp: Double, val varbitId: Int?) {
    EARTH_WARRIOR(Items.CHAMPION_SCROLL_6798, NPCs.EARTH_WARRIOR_CHAMPION_3057, 432.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_EARTH_WARRIOR_1452),
    GHOUL(Items.CHAMPION_SCROLL_6799, NPCs.GHOUL_CHAMPION_3059, 400.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_GHOUL_1453),
    GIANT(Items.CHAMPION_SCROLL_6800, NPCs.GIANT_CHAMPION_3058, 280.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_GIANT_1454),
    GOBLIN(Items.CHAMPION_SCROLL_6801, NPCs.GOBLIN_CHAMPION_3060, 128.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_GOBLIN_1455),
    HOBGOBLIN(Items.CHAMPION_SCROLL_6802, NPCs.HOBGOBLIN_CHAMPION_3061, 232.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_HOBGOBLIN_1456),
    IMP(Items.CHAMPION_SCROLL_6803, NPCs.IMP_CHAMPION_3062, 160.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_IMP_1457),
    JOGRE(Items.CHAMPION_SCROLL_6804, NPCs.JOGRE_CHAMPION_3063, 480.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_JOGRE_1458),
    LESSER_DEMON(Items.CHAMPION_SCROLL_6805, NPCs.LESSER_DEMON_CHAMPION_3064, 592.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_LESSER_DEMON_1459),
    SKELETON(Items.CHAMPION_SCROLL_6806, NPCs.SKELETON_CHAMPION_3065, 232.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_SKELETON_1460),
    ZOMBIE(Items.CHAMPION_SCROLL_6807, NPCs.ZOMBIES_CHAMPION_3066, 240.0, Vars.VARBIT_CHAMPIONS_CHALLENGE_ZOMBIE_1461),
    LEON(Items.CHAMPION_SCROLL_6808, NPCs.LEON_DCOUR_3067, 492.0, null);

    companion object {
        private val byScroll = values().associateBy { it.scrollId }
        fun fromScroll(scrollId: Int) = byScroll[scrollId]
    }
}
